backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'painting'
    label: 'Painting'
    folder: 'content/paint'
    create: true
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    identifier_field: 'slug'
    fields:
      - label: 'Slug'
        name: 'slug'
        description: 'A shortend title no longer than 30 characters'
        pattern: [ '^.{0,30}$', 'No more than 30 characters' ]
        widget: 'string' 
        required: 'true'
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Year Created', name: 'year', widget: 'datetime', date_format: 'YYYY', format: 'L' }
      - { label: 'Painting Image', name: 'painting', widget: 'image', allow_multiple: false }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'painting' }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Info Page'
        name: 'info'
        file: 'content/pages/info.yml'
        fields:
          - { label: 'Bio', name: 'body', widget: 'markdown' }
      - label: 'CV Page'
        name: 'cv'
        file: 'content/pages/cv.yml'
        fields:
          - { label: 'CV', name: 'body', widget: 'markdown' }
      
  


