backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'painting'
    label: 'Painting'
    folder: 'content/{{year}}/paint'
    create: true
    # slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Year Created', name: 'year', widget: 'datetime', date_format: 'YYYY'}
      - { label: 'Painting Image', name: 'painting', widget: 'image', allow_multiple: false}
      - { label: 'Description', name: 'description', widget: 'text' }


